### ISSUE TITLE
Salling Group (Føtex, Netto...)

### ISSUE THREAD

**Issue by Herover** [Herover/heissepreise#2]
See https://developer.sallinggroup.com/api-reference

**Comment by nightgolfer** [comment]
Wow, det er fantastisk! 😮

Selv hvis der ikke er adgang til Nettos varer (og jeg er ikke sikker på at de *ikke* er der!), så har deres Food Waste API original prisen med!

https://developer.sallinggroup.dev/apireference#food-waste

**Comment by Herover** [comment]
Der bliver kigget på at hente priser fra api, det virker lovende :)
